#Will start the gateway server @8080
server: 
    port: 8080

spring: 
    application:
    　　　　　　　name: api-gateway    

#Zuul routes. Here for /student path, we are routing to localhost:8090 with extra path after that.
zuul: 
   routes: 
       person: 
            url: 'http://localhost:8001'
    
#Ribbon is auto integrated with Zuul and for this exercise we are not using that.
ribbon: 
    eureka: 
      enabled: false
 
logging: 
    level:
        root: info
